# Must with format yyyy-mm-dd
# https://yaml.org/type/timestamp.html
sdate: 2023-12-01
edate: 2023-12-31

# check the keys of INTERVAL_MS_MAP in utils/var.py
timeframe: 1h

# different exchange has different format for the pair name
# ccxt mapped exchange specified symbol to their own internal standardised symbol
# // base asset or currency
# // ↓
# // ↓  quote asset or currency
# // ↓  ↓
# // ↓  ↓    settlement asset or currency
# // ↓  ↓    ↓
# // ↓  ↓    ↓
# 'BTC/USDT:BTC'  // BTC/USDT inverse perpetual swap contract funded in BTC
# 'BTC/USDT:USDT' // BTC/USDT linear perpetual swap contract funded in USDT
# 'ETH/USDT:ETH'  // ETH/USDT inverse perpetual swap contract funded in ETH
# 'ETH/USDT:USDT' // ETH/USDT linear perpetual swap contract funded in USDT
# https://docs.ccxt.com/#/
ccxt_sym: BTC/USDT:USDT

# threshold of abs(A/B-1)
threshold: 0.001
